development: &default
  adapter: postgresql
  database: dockerized_rails_development
  min_messages: WARNING
  pool: 5
  username: postgres
  host: db

test:
  <<: *default
  database: dockerized_rails_test

production:
  <<: *default
  database: dockerized_rails_production
