---
:verbose: true
:concurrency: 5
:timeout: 5
:queues:
  - default

# See:
# - https://github.com/mperham/sidekiq/blob/master/examples/config.yml
# - https://github.com/brainopia/sidekiq-limit_fetch
